import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Suspense } from "react";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className} suppressHydrationWarning={true}>
        <Suspense fallback={<div>Loading...</div>}>
           <ConvexClientProvider> 
            {children}
            </ConvexClientProvider>
      
        </Suspense>
      </body>
    </html>
  );
}